title = 'John Meguerian – Product Design Lead'
baseURL = 'https://johnmeguerian.com/'
languageCode = 'en-us'
disableKinds = ["taxonomy", "term", "RSS"]
ignoreErrors = ["error-disable-taxonomy"]

# allows hugo to access binaries installed with the ASDF version manager
# if this isn't set, hugo can't run node packages like postcss
[security.exec]
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$','^ASDF_DIR$', '^HOME$']

# allows hugo to access environment variables set by various hosting tools
[security.funcs]
getenv = ["^HUGO_", "^NETLIFY_", "^VERCEL_", "NODE_"]

[markup.goldmark.renderer]
unsafe = true
